### ISSUE TITLE
Partial duplication of Backupninja?

### ISSUE THREAD

**Issue by colans** [andreasnuesslein/runrestic#1]
Some of the core features of this project appear to be duplicating [Backupninja](https://0xacab.org/riseuplabs/backupninja).  We are very close to adding support for Restic in the merge request [Add restic support](https://0xacab.org/riseuplabs/backupninja/merge_requests/17).

Would it be possible to:
* Test Backupninja with Restic support, and help move that initiative forward, and also
* Keep this module for Restic-specific things that can't logically be added to Backupninja?

**Comment by andreasnuesslein** [comment]
I like the idea of something more agnostic and allround-y. 

However, if I understand correctly, neither restic-support nor prometheus-support are included in backupninja yet, right? 
I needed something fast and this here project already does what I need. And I prefer Python over Bash ;)

Re your title "duplication of backupninja": Most of the code is actually inspired and copied from https://github.com/witten/borgmatic .
I'm guessing there is a ton of tools like these out there, and while, as I said I like the idea of having a more generic tool, this here is just what I need at the moment and at last for my scenario it's production ready.

Thank you for the input though!

**Comment by colans** [comment]
The Restic support is done; just needs to be merged.  (We're using it in Production.)

Anyway, fair enough, but it would be great if someone like yourself could add Prometheus support to Backupninja (if you had time).
