### ISSUE TITLE
AttributeError: 'ResticRepository' object has no attribute 'log'

### ISSUE THREAD

**Issue by ivomarino** [andreasnuesslein/runrestic#10]
hi all, everything working fine, just getting this error after backup:

```
Traceback (most recent call last):
  File "/usr/local/bin/runrestic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/runrestic/commands/runrestic.py", line 127, in main
    run_configuration(config, args)
  File "/usr/local/lib/python3.7/site-packages/runrestic/commands/runrestic.py", line 96, in run_configuration
    logs['repositories'][repository] = repo.log
AttributeError: 'ResticRepository' object has no attribute 'log'
```

any ideas on that? Thanks

**Comment by andreasnuesslein** [comment]
hey @ivomarino,

thank you for reporting :)
it comes to the point where i should probably add tests to this project.

anyways: i'm aware of the bug and shall try to fix it asap

**Comment by ivomarino** [comment]
ok, great, thanks @andreasnuesslein, should I close this issue then?

**Comment by andreasnuesslein** [comment]
i got it :)

**Comment by Junker** [comment]
make a release please..

**Comment by andreasnuesslein** [comment]
> make a release please..

so just so you know: this sentence sounds very unfriendly even with the "please" in the end. it's still an imperative (like an order): "make a release."  and i wouldn't feel very inclined to help you.

however: there has been a release for this issue since Feb 26.  https://pypi.org/project/runrestic/

**Comment by Junker** [comment]
Sorry, i didn't mean to be unfriendly. English is not my mother tongue.

Please, can you make new release on github? last release here is 0.2.8.

**Comment by andreasnuesslein** [comment]
why dont you just use pypi? `pip install runrestic` is the easiest way anyways.
sure, i'll tag it here too

**Comment by Junker** [comment]
this is necessary for Arch Linux package (https://aur.archlinux.org/packages/runrestic/)

**Comment by andreasnuesslein** [comment]
@Junker well actually https://wiki.archlinux.org/index.php/Python_package_guidelines#Source   you can use Pypi as well ;)
either way: it's consistently version 0.3.0 now on github and pypi 

cheers
