### ISSUE TITLE
Support Docker

### ISSUE THREAD

**Issue by Louies89** [andreasnuesslein/runrestic#11]
Hi,
Thank you for the wonderful work.
I am trying to run this in docker container. But unable to do so.

Can anyone can help please?

**Comment by andreasnuesslein** [comment]
Could you elaborate on your setup? Is it supposed to backup contents within the docker container while also running within the container? 
Also: what seems to be the problem exactly?

**Comment by Louies89** [comment]
Yes if we volume mapping in docker it can take files from the volume mapped to specific backup service. Docker is easy to maintain and easy to spin up. So it is better to have Docker option too.

**Comment by andreasnuesslein** [comment]
@Louies89 
could you show me what the problem is? Do you get any kind of output?

**Comment by Louies89** [comment]
Hi,
I was implementing it 2/3 weeks ago, but later I moved to Duplicati, So now I cannot provide any info about the problem. 

But my suggestion is, Dockerise the library, so that people can use directly, instead of they trying to Dockerise it.

I feel, when we make a library we do lot of research and make it available to public, so the user of the library should not do same research make it workable.

So I suggest try to Dockersise so people shall directly use the library.

**Comment by andreasnuesslein** [comment]
Well... 
a) it's not a library.
b) thanks for the suggestion but I currently don't care about Docker.
c) "so that people can use directly" - they can, just `pip install runrestic`, I think that's pretty straight forward.

cheers.
