### ISSUE TITLE
Error with large number of files

### ISSUE THREAD

**Issue by molich** [andreasnuesslein/runrestic#16]
Hello

I have a Ubuntu 14.04.5 LTS system with a large number of files, doing a backup to OVH swift open stack, the backup ends well but when runrestic is computing the files added to the repo, runrestic crashes, this is the output of the process:

```
Files:           0 new,    10 changed, 421764 unmodified
Dirs:            0 new,     5 changed,     0 unmodified
Added:      2.698 MiB

processed 421774 files, 16.520 GiB in 6:22
snapshot fd661ba0 saved

Traceback (most recent call last):
  File "/usr/local/bin/runrestic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/runrestic/commands/runrestic.py", line 131, in main
    run_configuration(config, args)
  File "/usr/local/lib/python3.4/dist-packages/runrestic/commands/runrestic.py", line 88, in run_configuration
    rcs += repo.backup(config.get('backup'))
  File "/usr/local/lib/python3.4/dist-packages/runrestic/restic/__init__.py", line 68, in backup
    self.log['restic_backup'] = parse_backup(output)
  File "/usr/local/lib/python3.4/dist-packages/runrestic/restic/output_parser.py", line 9, in parse_backup
    added_to_the_repo = re.findall('Added to the repo:\s+(-?[0-9.]+ [a-zA-Z]*B)', output)[0]
IndexError: list index out of range
```

I think the problem is the large number of files but I don't know for sure. I tried to run runrestic in a Ubuntu 14.04.5 LTS with a few files and works fine but I tried in the other system and fails.

Greetings.

**Comment by andreasnuesslein** [comment]
Hey @molich , 

thanks for the bug report. Is is possible that on that certain host your `restic` (not **run**restic) version is older? It says `Added` and the regex is looking for `Added to the repo`.

cheers

**Comment by molich** [comment]
Hello,

I checked the installed version and that was the case, the version was 0.9.1, with the latest version, 0.9.5 works fine. 

Thank you very much for your response.
