### ISSUE TITLE
Fix the setup.py in pypi

### ISSUE THREAD

**Issue by fryfrog** [andreasnuesslein/runrestic#19]
The `setup.py` that comes out of your pypi package uses a handful of `setuptools` things, but has `from distutils.core import setup` which means they don't work. Maybe something about `poetry` change could fix that?

**Comment by fryfrog** [comment]
You've already fixed it in the package you publish on github, yay! *Might* be worth double checking what makes it into pypi.

**Comment by andreasnuesslein** [comment]
Thanks for your report :)

So apparently poetry still throws it's on setup.py there when running `poetry publish`. I do find the current solution acceptable though.
