### ISSUE TITLE
drop fastjsonschema for jsonschema

### ISSUE THREAD

**Issue by Henry78** [andreasnuesslein/runrestic#9]
I'm not a Python pro, but it seems to be feasible and simple to drop fastjsonschema for jsonschema to simplify packaging (jsonschema is mostly already available as dist package).

**Comment by andreasnuesslein** [comment]
hey @Henry78 , 
thank you for your comment :)

what do you mean by that? are you planning on making a `.deb` or `.rpm`? if you install runrestic with `pip` it will simply pull fastjsonschema anyways

**Comment by Henry78** [comment]
I just built an AUR package (arch linux) and plan to make a .deb package too.

I know that I may install it via pip, but as a seasoned systems administrator I like everything handled by the package manger as far as possible.

**Comment by Henry78** [comment]
I'm currently testing it "drop in replaced". 
-- 
lg Henry

Am 23. Jänner 2019 22:28:24 MEZ schrieb "Andreas Nüßlein" <notifications@github.com>:

**Comment by andreasnuesslein** [comment]
Hey @Henry78 I switched them out; you can remove the `replace_fastjsonschema_by_jsonschema.patch` from your PKGBUILD 

cheers

**Comment by Henry78** [comment]
Thank you!
